parameters:
  #foobar
services:
    controller.main:
        class: ShoppingCartBundle\Controller\MainController
        arguments: ["@repository.product", "@service.shopping_cart_processor", "@service.shopping_cart_product_manager"]

    repository.product:
        class: ShoppingCartBundle\Entity\ProductRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ["ShoppingCartBundle:Product"]

    service.shopping_cart_product_manager:
        class: ShoppingCartBundle\Services\ShoppingCartProductManager
        arguments: ["@session"]

    service.shopping_cart_processor:
        class: ShoppingCartBundle\Services\ShoppingCartProcessor
        arguments: ["@session", "@repository.product"]